openapi: 3.1.0
info:
  title: Book-Api
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://library-api-uo21.onrender.com
    description: Production server on render
tags:
  - name: Books
    description: Book-related endpoints
  - name: Authors
    description: Author-related endpoints
  - name: Users
    description: User-related endpoints
  - name: Genres
    description: Genre-related endpoints
paths:
  /books:
    $ref: paths/books.yaml
  /books/{bookId}:
    $ref: paths/books.yaml
  /authors:
    $ref: paths/authors.yaml
  /authors/{authorId}:
    $ref: paths/authors.yaml
  /users:
    $ref: paths/users.yaml
  /users/{userId}:
    $ref: paths/users.yaml
  /genres:
    $ref: paths/genres.yaml
  /genres/{genreId}:
    $ref: paths/genres.yaml
  
  
  
